carts/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Cart

app_name = 'carts'

urlpatterns = [
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('carts/', cart_detail, name='cart_detail'),
    path('carts/remove/<int:product_id>/', cart_remove, name='cart_remove'), 
    path('carts/remove-all//<int:product_id>', cart_all_remove, name='cart_all_remove'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('makeups.urls')), 
    path('', include('products.urls')), 
    path('', include('carts.urls')), 
    path('accounts/', include('allauth.urls')),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('products/', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail'), 
]

carts/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    active = models.BooleanField(default=False)
    quantity = models.PositiveSmallIntegerField(null=True, default=1)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

carts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .models import Cart, CartItem
from orders.models import Order, OrderItem
from orders.forms import OrderForm 

from django.core.exceptions import ObjectDoesNotExist

def get_cart_id(request):
    cart = request.session.session_key

    if not cart:
        cart = request.session.create()
    
    return cart

@login_required(login_url="/login")
def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = get_cart_id(request),
            user = request.user
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)

        if cart_item.quantity < cart_item.product.quantity:
            cart_item.quantity +=1 
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product, 
            quantity = 1, 
            cart = cart, 
            active = True 
        )
        cart_item.save()

    return redirect('carts:cart_detail')

@login_required(login_url="/login")
def cart_detail(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
        
        order_form = OrderForm()

    except ObjectDoesNotExist:
        pass

    if request.method == 'POST':
        user = request.user
        emailAddress = request.POST['emailAddress']
        shippingPostcode = request.POST['shippingPostcode']

        try:
            order_details = Order.objects.create(
                user = request.user, 
                total = total, 
                emailAddress = emailAddress,
                shippingPostcode = shippingPostcode 
            )
            order_details.save()

            for order_item in cart_items:
                oi = OrderItem.objects.create(
                    product = order_item.product.name,
                    quantity = order_item.quantity,
                    price = order_item.product.price,  
                    order = order_details
                )
                oi.save()

                products = Product.objects.get(id=order_item.product.id)
                products.quantity = int(order_item.product.quantity - order_item.quantity)
                products.save()
                order_item.delete()

                print('주문이 완료되었습니다.')

            return redirect('/')
        except ObjectDoesNotExist:
            pass 

    return render(request, 'carts/cart.html', dict(cart_items = cart_items, total = total, counter = counter, order_form = OrderForm))

@login_required(login_url="/login")
def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id = get_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()
    
    return redirect('carts:cart_detail')

@login_required(login_url="/login")
def cart_all_remove(request, product_id):
    cart = Cart.objects.get(cart_id = get_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('carts:cart_detail')

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

<style>
    .pop_wrap{
        background-color:rgba(0,0,0,.3); 
        justify-content:center; 
        align-items:center;   
        position:fixed;   
        top:0;
        left:0;
        right:0;
        bottom:0;               
        display:none; 
        padding:15px; 
    }  

    .pop_inner {
        border-radius:10px;
        background-color:#ffffff; 
        padding:30px; 
        box-shadow: 5px 10px 10px 1px rgba(0,0,0,.3); 
    }
</style>

{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center d-block p-3 bg-dark text-white">
            <h3> 장바구니</h3>
    </div>
    {% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                장바구니가 비어있습니다. 
            </h1>
            <br>
            <p class="text-center">
                <a href="{% url 'products:product_list' %}">이 곳</a>을 눌러 쇼핑을 계속 하세요. 
            </p>
        </div>
    </div>
    {% else %}
    <div class="row mx-auto">
        <div class="col-20 col-sm-15 col-md-15 col-lg-10 text-center">
            <table class="table my_custom_table">
                <thread class="my_custom_thread">
                    <tr>
                        <th colspan="5">
                            제품 목록
                        </th>
                    </tr>
                </thread>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="{% url 'products:product_detail' pk=cart_item.product.id %}">
                                <img src="{{ cart_item.product.image.url }}" width=100px height=100px alt="" class="float-left rounded custom_image">
                            </a>
                        </td>
                        <td class="text-left">
                            No.{{cart_item.product.id}} {{cart_item.product.name}}
                            <hr> 가격 : {{cart_item.product.price}} 원
                            <br> 총계 : {{cart_item.quantity}} 개 x {{cart_item.product.price}} 원        
                    
                        </td>
                        <td>
                            총액 : {{cart_item.sub_total}} 원
                        </td>
                        {% if cart_item.quantity < cart_item.product.quantity %}
                            <td>
                                <a href="{% url 'carts:add_cart' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/plus.png' %}" width=30em height=30em></a>&nbsp;
                                <a href="{% url 'carts:cart_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/minus.png' %}" width=15em height=15em ></a>&nbsp;
                                <br>
                                <a href="{% url 'carts:cart_all_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/delete.png' %}"width=20em height=20em></a>
                            </td>
                            {% else %}
                            <td>
                                &nbsp; <a href="" class="custom a"><i class="fas fa-minus-circle custom icon"></i></a>&nbsp;
                                <a href="" class="custom_a"><i class="fas fa-trash-alt custom_icon"></i></a>
                            </td>
                                <td></td>
                        {% endif %}
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-20 col-sm-15 col-md-15 col-lg-10 text-center">
            <table class="table my_custom_table">
                <thread class="my_custom_thread">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thread>
                <tbody>
                    <tr>
                        <td>
                            결제하기 전에 장바구니 목록을 확인하세요. 
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            합계 : <strong>{{ total }} 원</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'products:product_list' %}" class="btn btn-secondary btn-block my_custom_button">쇼핑 계속하기</a>
                <a href="#pop_info_1" class="btn_open btn btn-secondary btn-block my_custom_button">주문하기</a>
            </div>
            <br>
        </div>
    </div>

    
    <div id="pop_info_1" class="pop_wrap">
        <div class="text-center">
            <div class="pop_inner">
                    <h4>주문 정보 입력</h4>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                </br>
                    {{ order_form.as_p }}
                    <div class="d-flex justify-content-center">
                        <br>
                        <input class="btn btn-dark" type="submit" value="주문하기" />
                    </div>
                </form>
            </div>
        </div>
    </div>

    <br>
    {% endif %}

    
    <script>
        var target = document.querySelectorAll('.btn_open');
        var targetID;
      
        // 팝업 열기
        for(var i = 0; i < target.length; i++){
          target[i].addEventListener('click', function(){
            targetID = this.getAttribute('href');
            document.querySelector(targetID).style.display = 'block';
          });
        }
        
        // 팝업 닫기
        for(var j = 0; j < target.length; j++){
          btnPopClose[j].addEventListener('click', function(){
            this.parentNode.parentNode.style.display = 'none';
          });
        }
      </script>
      
{% endblock %}