accounts/urls.py
from django.urls import path, include

from .views import *
from .models import Profile

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', ProfileDetailView.as_view(), name="profile"),
    path('profile/update/', ProfileUpdateView.as_view(), name="profile-update"), 
]

carts/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Cart

app_name = 'carts'

urlpatterns = [
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('carts/', cart_detail, name='cart_detail'),
    path('carts/remove/<int:product_id>/', cart_remove, name='cart_remove'), 
    path('carts/remove-all//<int:product_id>', cart_all_remove, name='cart_all_remove'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('makeups.urls')), 
    path('', include('products.urls')), 
    path('', include('carts.urls')), 
    path('accounts/', include('allauth.urls')),
]

accounts/models.py
from django.conf import settings
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib import auth


class Profile(models.Model):
    user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(blank=True, upload_to='non-makeup')
    nickname = models.CharField(max_length=40, blank=True)
    bio = models.TextField(blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name','last_name']

class ProfileForm(forms.ModelForm):
    image = forms.ImageField(required=False) # 선택적으로 입력할 수 있음.
    class Meta:
        model = Profile
        fields = ['nickname','image', 'bio']

accounts/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.http import request
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User

from django.views.generic.detail import DetailView
from django.views import View
from .forms import UserForm, ProfileForm


def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                                            username=request.POST['username'],
                                            password=request.POST['password1'],
                                            email=request.POST['email'],)
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')
        return render(request, 'accounts/signup.html')
    return render(request, 'accounts/signup.html')

# 로그인
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')


# 로그아웃
def logout(request):
    auth.logout(request)
    return redirect('/')

# home
def home(request):
    return render(request, '/')

class ProfileDetailView(View):
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        return render(request, 'accounts/profile.html', {"profile_user":user})

class ProfileUpdateView(View):
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk)
        user_form = UserForm(initial={
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
        })

        if hasattr(user, 'profile'):
            profile = user.profile
            profile_form = ProfileForm(initial={
                'nickname': profile.nickname,
                'image': profile.image,
                'bio': profile.bio,
            })
        else:
            profile_form = ProfileForm()

        return render(request, 'accounts/profile_update.html', {"user_form": user_form, "profile_form": profile_form})

    def post(self, request):
        u = User.objects.get(id=request.user.pk)
        user_form = UserForm(request.POST, instance=u)

        if user_form.is_valid():
            user_form.save()

        if hasattr(u, 'profile'):
            profile = u.profile
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        else:
            profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = u
            profile.save()

        return redirect('accounts:profile')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load socialaccount %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="d-flex justify-content-center d-block p-3 bg-dark text-white">
        <h3>로그인</h3>
    </div>
<br/>
<div class="container">
    <div class="d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            ID:
            <br>
            <input name="username" type="text">
            <br>
            Password:
            <br>
            <input name="password" type="password">
            <br><br>
            <div class="d-flex justify-content-center">
                <input type="submit" class="btn btn-dark" value="Login">
            </div>
        </form>
    </div>
    <br/>
    <div class="d-flex justify-content-center">
        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>&nbsp&nbsp Log in with Google</a>
    </div>
</div>
    </br>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    </br>
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="row">
                <div class="col">
                    {% if profile_user.profile.image %}
                    <img class="round" src="{{profile_user.profile.image.url}}" height="90%", width="90%"> <br>
                    {% else %}
                    <img class="round" src="{% static 'assets/user.png' %}" height="200"width="200"> <br>
                    {% endif %}
                    </br>
                </div>
                <div class="col">
                    <h3> ID: {{profile_user.username}} </h3>
                    <hr>
                    <h5>닉네임: {{profile_user.profile.nickname}}</h5>
                    <h5> 이름: {{profile_user.last_name}} {{profile_user.first_name}} </h5>
                    <h5> 소개: {{profile_user.profile.bio}} </h5>
                    </br>
                    <div class="d-flex justify-content-center">
                        {% if user == profile_user %}
                        <a href="{% url 'accounts:profile-update' %}">
                            <button type="button" class="btn btn-dark">프로필 편집</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </br>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="d-flex justify-content-center d-block p-3 bg-dark text-white">
    <h3>{{user.username}}의 Profile Update</h3>
</div>
<div class="container">
    <div class="d-flex justify-content-center">
            {% if error_msg %}
            <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error</strong> {{error_msg}}
            </div>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                </br>
                {{ user_form | crispy }}
                {{ profile_form  | crispy }}
                <br/>
                <div class="d-flex justify-content-center">
                    <input class="btn btn-dark" type="submit" value="Update" />
                </div>
            </form>
        </p>
    </div>
</div>
</br>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="d-flex justify-content-center d-block p-3 bg-dark text-white">
    <h3>로그인</h3>
</div>
<br/>
<div class="container">
    <div class="d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            아이디: <br>
            <input name="username" type="text">
            <br>
            비밀번호: <br>
            <input name="password1" type="password">
            <br>
            비밀번호 확인: <br>
            <input name="password2" type="password">
            <br>
            이메일: <br>
            <input name="email" type="email">
            <br><br>
            <div class="d-flex justify-content-center">
                <input type="submit" class="btn btn-dark" value="회원가입">
            </div>
        </form>
    </div>
</div></br>
{% endblock %}