carts/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Cart

app_name = 'carts'

urlpatterns = [
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('carts/', cart_detail, name='cart_detail'),
    path('carts/remove/<int:product_id>/', cart_remove, name='cart_remove'), 
    path('carts/remove-all//<int:product_id>', cart_all_remove, name='cart_all_remove'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('makeups.urls')), 
    path('', include('products.urls')), 
    path('', include('carts.urls')), 
    path('accounts/', include('allauth.urls')),
]

makeups/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Makeup

app_name = 'makeups'

urlpatterns = [
    path('', makeup_list, name='makeup_list'),
    path('makeups/', makeup_register, name='makeup_register'), 
    path('makeups/detail/<int:pk>/', makeup_detail, name='makeup_detail'),
    path('makeups/detail/<int:pk>/makeup/',virtual_makeup, name='virtual_makeup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('products/', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail'), 
]

makeups/models.py
from config.models import Timestamp
from products.models import Product

import reserve as reserve
from django.db import models
from django.contrib.auth.models import User

class Makeup(Timestamp):
    products = models.ManyToManyField(Product, blank=True)
    image = models.ImageField(upload_to='reference')
    title = models.CharField(max_length=100)
    detail = models.TextField()

    def get_absolute_url(self):
        return reserve('makeups:makeup_detail', args=[str(self.id)])

makeups/forms.py
from django.forms import ModelForm
from django import forms

from .models import Makeup
from  products.models import Product

class MakeupModelForm(ModelForm):
    class Meta:
        model = Makeup
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'detail': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
            'products': forms.CheckboxSelectMultiple,
        }
        
        labels = {
            'products': '사용된 메이크업 제품',
            'image': '메이크업 이미지',
            'title': '이름',
            'detail': '설명',
        }  

makeups/views.py
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect

from accounts.models import Profile

from .models import Makeup
from .forms import MakeupModelForm 

def makeup_list(request):
    makeups = Makeup.objects.all()
    return render(request, 'makeups/index.html', {'makeups': makeups})

@login_required(login_url="/login")
def makeup_register(request):
    if request.method == 'POST':
        form = MakeupModelForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            makeup = Makeup.objects.create(
                image=data['image'],
                title=data['title'],
                detail=data['detail'],
            )

            products = data.get('products')
            for product in products.iterator():
                makeup.products.add(product)

            makeup.save()

            return redirect('makeups:makeup_detail', pk=makeup.id)
    else:
        form = MakeupModelForm()
    return render(request, 'makeups/makeup_register.html', {'form': form})


def makeup_detail(request, pk):
    makeup = Makeup.objects.get(pk=pk)
    products = makeup.products.all()
    return render(request, 'makeups/makeup_detail.html', {'object': makeup, 'products': products})

@login_required(login_url="/login")
def virtual_makeup(request, pk):
    makeup = Makeup.objects.get(pk=pk)

    makeup_image = str(makeup.image)
    user_image = str(request.user.profile.image)

    root = 'CPM/imgs/'

    save_path = root + 'results/'

    cmd = f'CUDA_VISIBLE_DEVICES=0 python CPM/main.py --style {root}{makeup_image} --input {root}{user_image}  --savedir {save_path} --filename {pk}_{request.user.id}.png'

    os.system(cmd)

    result = f'/{save_path}{pk}_{request.user.id}.png'

    return render(request, 'makeups/result.html', {'makeup': makeup, 'result': result})

makeups/templates/makeups/index.html
{% extends 'base.html' %}

{% block content %}
        <!-- Header-->
<div class="container px-3 px-lg-3">
    <div class="main_left1">
        <img src="https://static.wixstatic.com/media/1a636a537d504dc2af0174f314f6655c.jpg/v1/fill/w_554,h_680,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1a636a537d504dc2af0174f314f6655c.jpg">
    </div>
    <div class="main_right1">
        <br><br><br><br><br><br><br>
        <h1 class="font_2" style="line-height:1.25em; text-align:center; font-size:72px;">
            <span style="letter-spacing:normal;">
                <span class="color_15">
                    <span style="font-weight:bold;"><span>
                        <span>welcome to <br> Cosmetheic</span><br>
        <p class="font_7" style="line-height:1.67em; text-align:center; font-size:20px;">
            <span style="font-family:맑은 고딕,malgun gothic,apple sd gothic neo,applegothic,sans-serif;">
                <span style="font-weight:bold;">
                    <span style="letter-spacing:normal;">
                        <span class="color_15">​가상 메이크업 쇼핑몰 💄</span></h1>
    </div>

    <div class="main_center1">
        <div data-mesh-id="comp-l8q3n24f2inlineContent-gridContainer" data-testid="mesh-container-content">
            <div id="comp-l8q3n24g" class="_2Hij5 _3bcaz" data-testid="richTextElement">
                <br><br><br><br>
                <h2 class="font_4" style="line-height:1.35em; text-align:center; font-size:40px;">
                    <span style="font-weight:bold;">다양한 가상의 메이크업으로
                        <br>자신만의 메이크업을 찾으세요!</span>
                </h2>
            </div>
            <div id="comp-l8q3n24g1" class="_2Hij5 _3bcaz" data-testid="richTextElement">
                <p class="font_8" style="line-height:1.75em; text-align:center; font-size:18px;">
                    <span style="font-family:futura-lt-w01-book,futura-lt-w05-book,sans-serif;">
                        다양하게 제공되는 레퍼런스 이미지를 통해 이제는 메이크업 도구 없이 가상의 화장을 체험해 보세요.</span>
                </p><br><br><br>
            </div>

            <div class="main_left1">
                <img src="https://static.wixstatic.com/media/e5fea9_46e05ab2518b44dd91683cf30d17b1c0~mv2.png/v1/fill/w_490,h_440,al_c,lg_1,q_85,enc_auto/e5fea9_46e05ab2518b44dd91683cf30d17b1c0~mv2.png"></wix-image>
            </div>
            <div class="main_right1">
                <br><br><br><br><br><br><br><br><br><br><br><br>
                <div class="offset-1">
                <h3 class="font_6" style="line-height:1.41em; text-align:left; font-size:22px;">
                    <span style="letter-spacing:normal;">
                        <span class="color_15">
                            <span style="font-weight:bold;">자신의 컬러에 맞게</span></span></span></h3>

                <p class="font_8" style="font-size:15px; line-height:1.75em; text-align:left;">
                    <span style="font-family:futura-lt-w01-book,futura-lt-w05-book,sans-serif;">
                        <span style="font-size:15px;">
                            <span style="letter-spacing:normal;">​화장품의 색깔은 다양합니다. 그중에서 당신에게 어울리는 색깔은 무엇인가요 <br>
                                Cosmethetic에서 가상 메이크업을 통해 당신에게 어울리는 색을 찾아보세요. <br> 자신의 컬러를 알 수 있습니다.</span></span></span></p>
<!--                <p class="font_8" style="font-size:15px; line-height:1.75em; text-align:left;">-->
<!--                    <span style="font-family:futura-lt-w01-book,futura-lt-w05-book,sans-serif;">-->
<!--                        <span style="font-size:15px;">-->
<!--                            <span style="letter-spacing:normal;">자신의 컬러를 알 수 있습니다.</span></span></span></p>-->
                </div>
            </div>

            <div class="main_left1">
                <br><br><br><br><br><br><br><br><br><br><br><br>
                <div class="offset-1">
                    <h3 class="font_6" style="line-height:1.41em; text-align:left; font-size:22px;">
                    <span style="letter-spacing:normal;">
                        <span class="color_15">
                            <span style="font-weight:bold;">​새로움을 추구하는 메이크업</span></span></span></h3>
                <p class="font_8" style="font-size:15px; line-height:1.75em; text-align:left;">
                    <span style="font-family:futura-lt-w01-book,futura-lt-w05-book,sans-serif;">
                        <span style="font-size:15px;">
                            <span style="letter-spacing:normal;">필요 이상으로 많은 화장도구와 늘 새롭게 변신하는 화장 스타일을 가상 <br>
                                메이크업을 통해 쉽게 도전 해보세요.<br>
                                이상적인 메이크업과 새로움을 추구하는 메이크업을 가상에서 받고<br>
                                만족감을 얻으세요.</span></span></span></p>
                    </div>
            </div>
            <div class="main_right1">
                <img src="https://static.wixstatic.com/media/11062b_627113da20a64adf851f2e5909e46c33~mv2_d_6360_3744_s_4_2.jpg/v1/fill/w_490,h_440,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/11062b_627113da20a64adf851f2e5909e46c33~mv2_d_6360_3744_s_4_2.jpg"></wix-image>
            </div>

            <div class="main_center1">
                <div class="offset-2">
                <br><br>
                <span style="text-align:left; font-size:30px;">
                    <span>가상 메이크업 시도하기</span>
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <button type="button" class="btn btn-outline-danger">make up</button>
                </span><br><br></div>
            <div id="carouselExampleIndicators" class="latest-slider-tb carousel slide carousel-tb" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                </div>

            <div class="carousel-inner" style="text-align: center;">
                <div class="carousel-item active">
                    <img class="img-responsive center-block" src="https://static.wixstatic.com/media/e5fea9_aaa84c59a0cd43259d39cee42da25309~mv2.jpg/v1/fill/w_309,h_309,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/e5fea9_aaa84c59a0cd43259d39cee42da25309~mv2.jpg" class="d-block w-45" style="text-align: center;object-position: 50% 50%" >
                    <br><br>
                    <span style="">감각적인 레드 립 메이크업</span>
                </div>
                <div class="carousel-item">
                    <img class="img-responsive center-block" src="https://static.wixstatic.com/media/e5fea9_3c780d56ba5e42328d38e2e56267403e~mv2.jpg/v1/fill/w_309,h_309,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/e5fea9_3c780d56ba5e42328d38e2e56267403e~mv2.jpg" class="d-block w-45" alt="...">
                    <br><br>
                    <span style="">꽃처럼 피어나는 화사한 브러셔 메이크업</span>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
    </div> <br><br>

            </div>
<!--        <header class="bg-dark py-5">-->
<!--            <div class="container px-4 px-lg-5 my-5">-->
<!--                <div class="text-center text-white">-->
<!--                    <h1 class="display-4 fw-bolder">Welcome to Cosmethetic 💄</h1>-->
<!--                    <h4 class="text-white-50 mb-0">가상 메이크업 쇼핑몰 서비스</h4>-->
<!--                    <br>-->
<!--                </div>-->
<!--            </div>-->
<!--        </header>-->
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                    {% for makeup in makeups %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ makeup.image.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <!-- <h5 class="fw-bolder">{{ product.name }}</h5> -->
                                        <!-- Product price-->
                                        <!-- {{ product.price }} 원 -->
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'makeups:makeup_detail' pk=makeup.id %}">View products</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </section>
{% endblock %}

makeups/templates/makeups/intro.html
{% extends 'base.html' %}

{% block content %}

<div class="main_center1">
    <br><br><br><br><br>
    <h2 class="font_4" style="line-height:1.35em; text-align:center; font-size:60px;">
        <span style="font-weight:bold;"> 소개 </span>
    </h2>
    <br><br>
    <p class="font_9" style="text-align:center; line-height:1.875em; font-size:20px;">
        <span class="color_15">
            Cosmethetic은 인공지능이 탑재된 가상 메이크업 화장품 쇼핑몰 서비스를 제공합니다.<br>
            사용자의 이미지 위에 화장도구 없이 원하는 화장을 해보세요!<br><br>
            가상 메이크업을 통해 시도하지 못했던 이미지를 얼마든지 바꿀 수 있습니다.<br>
            또한 어울리는 컬러를 찾을 수 있습니다.
        </span></p> <br><br>


</div>


{% endblock %}

makeups/templates/makeups/makeup_detail.html
{% extends 'base.html' %}

{% block content %}
    </br>
    <div class="container">
        <div class="row">
            <div class="col">
                <p><img src="{{ object.image.url }}" class="img-thumbnail"></p>
            </div>
            <div class="col-8">
                <div class="col">
                    <h3>{{ object.title }}</h3>
                    <hr />
                    <p>{{ object.detail }}</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'makeups:virtual_makeup' pk=object.id %}"><button type="button" class="btn btn-dark">메이크업 해보기</button></a>
                    <!-- <button type="button" class="btn btn-outline-dark">연락하기</button> -->
                    {% endif %}
                </div>
            </div>
        </div>
    

        <section class="py-5">
            <h3>사용 제품</h3>
            <hr />
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">


                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product price-->
                                    {{ product.price }} 원
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a href="{% url 'products:product_detail' pk=product.id %}"><button type="button" class="btn btn-dark">자세히 보기</button></a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>

    </div>
    </br>
{% endblock %}

makeups/templates/makeups/makeup_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex justify-content-center d-block p-3 bg-dark text-white">
    <h3>메이크업 등록</h3>
</div>
<br />
<div class="container">
    <div class="d-flex justify-content-center">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form | crispy }}
            {% csrf_token %}
        </br>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-dark">등록하기</button>
        </div>
    </form>
    </div>
</div>

{% endblock %}

makeups/templates/makeups/result.html
{% extends 'base.html' %}

{% block content %}
    </br>
    <div class="d-flex justify-content-center">
        <div class="container">
          <div class="row">
              <div class="col-lg-4">
                <figure class="figure">
                  <img src="{{ request.user.profile.image.url }}" class="figure-img img-fluid rounded" alt="...">
                  <figcaption class="figure-caption text-center">내 사진</figcaption>
                </figure>
              </div>
              <div class="col-lg-4">
                <figure class="figure">
                  <img src="{{ makeup.image.url }}" class="figure-img img-fluid rounded" alt="...">
                  <figcaption class="figure-caption text-center">메이크업 사진</figcaption>
                </figure>
              </div>
              <div class="col-lg-4">
                    <figure class="figure">
                      <img src="{{ result }}" width=512 height=512 class="figure-img img-fluid rounded" alt="...">
                      <figcaption class="figure-caption text-center">virtual try on</figcaption>
                    </figure>
                </div>
              </div>
          </div>
        </div>
    </div>
    </br>
{% endblock %}