accounts/urls.py
from django.urls import path, include

from .views import *
from .models import Profile

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', ProfileDetailView.as_view(), name="profile"),
    path('profile/update/', ProfileUpdateView.as_view(), name="profile-update"), 
]

carts/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Cart

app_name = 'carts'

urlpatterns = [
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('carts/', cart_detail, name='cart_detail'),
    path('carts/remove/<int:product_id>/', cart_remove, name='cart_remove'), 
    path('carts/remove-all//<int:product_id>', cart_all_remove, name='cart_all_remove'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('makeups.urls')), 
    path('', include('products.urls')), 
    path('', include('carts.urls')), 
    path('accounts/', include('allauth.urls')),
]

makeups/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *
from .models import Makeup

app_name = 'makeups'

urlpatterns = [
    path('', makeup_list, name='makeup_list'),
    path('makeups/', makeup_register, name='makeup_register'), 
    path('makeups/detail/<int:pk>/', makeup_detail, name='makeup_detail'),
    path('makeups/detail/<int:pk>/makeup/',virtual_makeup, name='virtual_makeup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('products/', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail'), 
]

templates/base.html
{% load static %}

<!DOCTYPE html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Cosmethetic</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" {% static 'assets/favicon.ico' %} />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- font -->
        <style>
            @font-face {
                font-family: 'Pretendard-Regular';
                src: url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff') format('woff');
                font-weight: 400;
                font-style: normal;
            }
            body {
                font-family: 'Pretendard-Regular';
            }
        </style>

        {% block style %}
        {% endblock %}
   </head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'makeups:makeup_list' %}">💄 Cosmethetic</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link" href="{% url 'makeups:makeup_register' %}">메이크업 등록</a></li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'products:product_list' %}">All Products</a></li>
                            <li><a class="dropdown-item" href="{% url 'makeups:makeup_list' %}">All Makeups</a></li>
                            <!-- <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li> -->
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'accounts:profile' %}" class="nav-link">Welcone, {{ user.get_username }}</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a></li>
                        <form class="d-flex">
                            <button class="btn btn-outline-dark" type="submit">
                                <a style='text-decoration:none; color:black;' href='{% url "carts:cart_detail" %}'> 
                                <i class="bi-cart-fill me-1"></i>
                                Cart
                                <span class="badge bg-dark text-white ms-1 rounded-pill">{{ item_count }}</span>
                                </a>
                            </button>
                        </form>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark mt-auto">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; myunbongs 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
</body>
</html>